### ISSUE TITLE
能否通过 Netty 代替 Spring MVC 

### ISSUE THREAD

**Issue by kakayikaka** [LoongmaSpirit/weixin-subscription-server#4]
我有多个微信公众号需要管理，而且想通过一个服务器同时管理这些账户。所以对吞吐量的要求比较高，而且还想后续支持横向扩展。所以能否用 Netty 代替 MVC？

**Comment by LoongmaSpirit** [comment]
对于这类单体应用，mvc实现较为方便，如果使用tomcat这类http容器的话，吞吐量也还行。

不过后续有时间可以考虑出一版 netty 版的。
